"use client";
import { FormEvent, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowUp, CloudSun, MapPin, ShieldCheck, Sparkles, Wind, Droplets, Sun, Thermometer, ChevronDown, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";

type Reply = { answer: string; status: string; location?: {name:string;country:string}; weather?: {temperature_2m:number|null;wind_speed_10m:number|null;precipitation_probability:number|null;uv_index:number|null;observed_at:string;timezone:string;source:string}; policy?: {outcome:string;sop_id?:string;title?:string;severity?:string;trace?:{sop_id:string;matched:boolean;detail:string}[]}; trace:string[] };
type Turn = { question:string; answer?:string; status?:string; at:string };
// Vercel Services routes this same-origin path to FastAPI. Local development
// keeps the standalone backend URL unless NEXT_PUBLIC_API_URL overrides it.
const API = process.env.NEXT_PUBLIC_API_URL || (process.env.NODE_ENV === "development" ? "http://localhost:8000" : "");
function sessionId() { if (typeof window === "undefined") return ""; let id=sessionStorage.getItem("weatherwise-session"); if(!id){id=crypto.randomUUID();sessionStorage.setItem("weatherwise-session",id);} return id; }

export default function Home() {
 const [input,setInput]=useState(""); const [reply,setReply]=useState<Reply|null>(null); const [turns,setTurns]=useState<Turn[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [traceOpen,setTraceOpen]=useState(false);
 async function ask(text:string) { if(!text.trim()||loading)return; setInput("");setReply(null);setLoading(true);setError("");setTurns(prev=>[...prev,{question:text,at:new Date().toISOString()}]); try { const response=await fetch(`${API}/api/chat`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({session_id:sessionId(),message:text})}); if(!response.ok)throw new Error("The advisory service returned an error. Please try again."); const data:Reply=await response.json(); setReply(data); setTurns(prev=>prev.map((turn,index)=>index===prev.length-1?{...turn,answer:data.answer,status:data.status}:turn)); } catch(e) { const message=e instanceof Error?e.message:"Could not reach the advisory service."; setError(message);setTurns(prev=>prev.map((turn,index)=>index===prev.length-1?{...turn,answer:message,status:"error"}:turn)); } finally {setLoading(false);} }
 function submit(e:FormEvent){e.preventDefault();void ask(input);}
 const suggestions=["Is it safe to cycle in Bhopal today?","Should I take my child to the park in Pune this afternoon?","Is today a good day for a picnic in Jaipur?"];
 return <main className="shell min-h-screen"><header className="topbar"><a className="brand" href="#"><span className="brand-icon"><CloudSun size={20}/></span>weatherwise</a><div className="top-note"><span className="live-dot"/>LIVE CONDITIONS <span className="divider">/</span> SOP-GROUNDED</div></header>
 <section className="hero"><div className="eyebrow"><Sparkles size={14}/> YOUR OUTDOOR SAFETY COMPANION</div><h1>Make plans with<br/><em>the weather</em> in mind.</h1><p className="lede">Ask about an outdoor activity. Get a clear recommendation grounded in live local weather and written safety policies.</p>
 <div className="input-card"><div className="input-heading"><span>WHAT ARE YOU PLANNING?</span><span className="input-hint">A place and activity work best</span></div><form onSubmit={submit}><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="e.g. Is it safe to go for a run in Bengaluru this evening?" rows={2} maxLength={1000} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void ask(input);}}}/><Button className="send" size="icon" disabled={!input.trim()||loading} aria-label="Get advisory">{loading?<span className="spinner"/>:<ArrowUp size={19}/>}</Button></form><div className="input-footer"><span><ShieldCheck size={14}/> Your question is evaluated against written policies</span><span>{input.length}/1000</span></div></div>
 <div className="suggestions"><span>TRY ASKING</span>{suggestions.map(s=><button key={s} onClick={()=>void ask(s)}>{s}</button>)}</div></section>
 {turns.length>0&&<section className="conversation" aria-label="Conversation">{turns.map((turn,index)=><article className="turn" key={`${turn.at}-${index}`}><div className="user-turn"><span>YOU · {new Date(turn.at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</span><p>{turn.question}</p></div>{index<turns.length-1&&turn.answer&&<div className="assistant-turn"><span>WEATHERWISE · {turn.status?.replaceAll("_"," ").toUpperCase()}</span><p>{turn.answer}</p></div>}{index===turns.length-1&&loading&&<div className="assistant-turn pending"><span>WEATHERWISE</span><p><i className="spinner dark"/> Checking the requested forecast and policy…</p></div>}</article>)}</section>}
 <AnimatePresence>{error&&<motion.div className="error" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}>{error} <button onClick={()=>setError("")}>Dismiss</button></motion.div>}</AnimatePresence>
 <AnimatePresence>{reply&&<motion.section className="result" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.35}}>
   <div className="result-head"><div><div className="eyebrow"><span className={reply.status==="matched"?"live-dot":"muted-dot"}/>{reply.status==="no_policy"?"NO POLICY MATCH":reply.status.replaceAll("_"," ").toUpperCase()}</div><h2>Your advisory</h2></div><button className="icon-button" title="Clear conversation" onClick={()=>{setReply(null);setTurns([]);sessionStorage.removeItem("weatherwise-session");setTraceOpen(false);}}><RotateCcw size={16}/></button></div>
   <p className="answer">{reply.answer}</p>
   {reply.location&&<div className="location"><MapPin size={15}/>{reply.location.name}, {reply.location.country}</div>}
   {reply.weather&&<><div className="weather-label">FORECAST SNAPSHOT <span>{reply.weather.observed_at?.replace("T"," · ")} · {reply.weather.timezone}</span></div><div className="weather-grid"><Metric icon={<Thermometer/>} label="Temperature" value={reply.weather.temperature_2m==null?"—":`${reply.weather.temperature_2m}°C`}/><Metric icon={<Wind/>} label="Wind" value={reply.weather.wind_speed_10m==null?"—":`${reply.weather.wind_speed_10m} km/h`}/><Metric icon={<Droplets/>} label="Rain chance" value={reply.weather.precipitation_probability==null?"—":`${reply.weather.precipitation_probability}%`}/><Metric icon={<Sun/>} label="UV index" value={reply.weather.uv_index==null?"—":reply.weather.uv_index}/></div></>}
   {reply.policy?.sop_id&&<div className="citation"><ShieldCheck size={17}/><div><b>{reply.policy.sop_id} · {reply.policy.title}</b><span>{reply.policy.severity} SEVERITY · DETERMINISTIC POLICY</span></div></div>}
   <button className="trace-toggle" onClick={()=>setTraceOpen(!traceOpen)}>Engineering trace <ChevronDown size={15} className={traceOpen?"turned":""}/></button>{traceOpen&&<ol className="trace">{reply.trace.map((x,i)=><li key={i}>{x}</li>)}{reply.policy?.trace?.map((x,i)=><li key={`policy-${i}`}>{x.sop_id}: {x.detail}</li>)}</ol>}
 </motion.section>}</AnimatePresence>
 <footer><span>Weather facts from <b>{reply?.weather?.source || "Open-Meteo"}</b></span><span>Safety decisions from written SOPs</span></footer></main>
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string|number}) {return <div className="metric"><span className="metric-icon">{icon}</span><span className="metric-label">{label}</span><b>{value}</b></div>}
