"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowUp, CloudSun, MapPin, ShieldCheck, Sparkles, Wind, Droplets, Sun, Thermometer, ChevronDown, RotateCcw, LocateFixed, Mic, MicOff, Volume2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { GeminiLiveVoice, type CurrentLocation, type VoiceLanguage, type VoiceStatus } from "@/lib/voice";

type Reply = { answer: string; status: string; location?: {name:string;country:string}; weather?: {temperature_2m:number|null;wind_speed_10m:number|null;precipitation_probability:number|null;uv_index:number|null;observed_at:string;timezone:string;source:string}; policy?: {outcome:string;sop_id?:string;title?:string;severity?:string;trace?:{sop_id:string;matched:boolean;detail:string}[]}; trace:string[] };
type Turn = { question:string; answer?:string; status?:string; at:string };
type LocationState = "idle" | "requesting" | "ready" | "denied" | "error";
const VOICE_LANGUAGES: { code: VoiceLanguage; label: string }[] = [
 {code:"en-IN",label:"English"},{code:"te-IN",label:"తెలుగు"},{code:"hi-IN",label:"हिन्दी"},{code:"ta-IN",label:"தமிழ்"},
 {code:"kn-IN",label:"ಕನ್ನಡ"},{code:"ml-IN",label:"മലയാളം"},{code:"mr-IN",label:"मराठी"},{code:"bn-IN",label:"বাংলা"},
];
// Vercel Services routes this same-origin path to FastAPI. Local development
// keeps the standalone backend URL unless NEXT_PUBLIC_API_URL overrides it.
const API = process.env.NEXT_PUBLIC_API_URL || (process.env.NODE_ENV === "development" ? "http://localhost:8000" : "");
function sessionId() { if (typeof window === "undefined") return ""; let id=sessionStorage.getItem("weatherwise-session"); if(!id){id=crypto.randomUUID();sessionStorage.setItem("weatherwise-session",id);} return id; }

export default function Home() {
 const [input,setInput]=useState(""); const [reply,setReply]=useState<Reply|null>(null); const [turns,setTurns]=useState<Turn[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [traceOpen,setTraceOpen]=useState(false);
 const [locationState,setLocationState]=useState<LocationState>("idle"); const [currentLocation,setCurrentLocation]=useState<CurrentLocation|null>(null); const [voiceStatus,setVoiceStatus]=useState<VoiceStatus>("idle"); const [voiceLanguage,setVoiceLanguage]=useState<VoiceLanguage>("en-IN"); const [voiceMessage,setVoiceMessage]=useState(""); const [voiceInput,setVoiceInput]=useState(""); const [voiceOutput,setVoiceOutput]=useState(""); const voiceRef=useRef<GeminiLiveVoice|null>(null);
 useEffect(()=>()=>{void voiceRef.current?.stop()},[]);
 function detectLocation(){if(!navigator.geolocation){setLocationState("error");setError("Live location is not available in this browser. You can still enter a city manually.");return;}setLocationState("requesting");navigator.geolocation.getCurrentPosition(p=>{setCurrentLocation({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,timestamp:new Date(p.timestamp).toISOString()});setLocationState("ready");setError("")},()=>{setLocationState("denied");setError("Location access was not granted. You can continue with a city name instead.")},{enableHighAccuracy:true,timeout:10000,maximumAge:30000})}
 async function startVoice(){if(voiceRef.current||voiceStatus==="connecting")return;const client=new GeminiLiveVoice(API,sessionId(),voiceLanguage,{getCurrentLocation:()=>currentLocation,onStatus:(s,m)=>{setVoiceStatus(s);setVoiceMessage(m||"")},onInputTranscript:t=>setVoiceInput(t),onOutputTranscript:t=>setVoiceOutput(p=>p?p+" "+t:t),onAdvisory:(d,q)=>{setReply(d as Reply);setTurns(p=>[...p,{question:q||"Voice request",answer:d.answer,status:d.status,at:new Date().toISOString()}])}});voiceRef.current=client;try{await client.start()}catch(e){voiceRef.current=null;setVoiceStatus("error");setVoiceMessage(e instanceof Error?e.message:"Could not start voice.")}}
 async function stopVoice(){await voiceRef.current?.stop();voiceRef.current=null;setVoiceStatus("idle");setVoiceMessage("")}
 async function ask(text:string) { if(!text.trim()||loading)return; setInput("");setReply(null);setLoading(true);setError("");setTurns(prev=>[...prev,{question:text,at:new Date().toISOString()}]); try { const response=await fetch(`${API}/api/chat`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({session_id:sessionId(),message:text,current_location:currentLocation})}); if(!response.ok)throw new Error("The advisory service returned an error. Please try again."); const data:Reply=await response.json(); setReply(data); setTurns(prev=>prev.map((turn,index)=>index===prev.length-1?{...turn,answer:data.answer,status:data.status}:turn)); } catch(e) { const message=e instanceof Error?e.message:"Could not reach the advisory service."; setError(message);setTurns(prev=>prev.map((turn,index)=>index===prev.length-1?{...turn,answer:message,status:"error"}:turn)); } finally {setLoading(false);} }
 function submit(e:FormEvent){e.preventDefault();void ask(input);}
 const suggestions=["Is it safe to cycle in Bhopal today?","Should I take my child to the park in Pune this afternoon?","Is today a good day for a picnic in Jaipur?"];
 return <main className="shell min-h-screen"><header className="topbar"><a className="brand" href="#"><span className="brand-icon"><CloudSun size={20}/></span>weatherwise</a><div className="top-actions"><button className={`location-chip ${locationState}`} onClick={detectLocation} type="button" disabled={locationState==="requesting"}><LocateFixed size={14}/>{locationState==="requesting"?"LOCATING…":locationState==="ready"?"LOCATION READY":"USE MY LOCATION"}</button><div className="top-note"><span className="live-dot"/>LIVE CONDITIONS <span className="divider">/</span> SOP-GROUNDED</div></div></header>
 <section className="hero"><div className="eyebrow"><Sparkles size={14}/> YOUR OUTDOOR SAFETY COMPANION</div><h1>Make plans with<br/><em>the weather</em> in mind.</h1><p className="lede">Ask about an outdoor activity. Get a clear recommendation grounded in live local weather and written safety policies.</p>
 <div className="input-card"><div className="input-heading"><span>WHAT ARE YOU PLANNING?</span><span className="input-hint">A place and activity work best</span></div><form onSubmit={submit}><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="e.g. Is it safe to go for a run in Bengaluru this evening?" rows={2} maxLength={1000} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void ask(input);}}}/><Button className="send" size="icon" disabled={!input.trim()||loading} aria-label="Get advisory">{loading?<span className="spinner"/>:<ArrowUp size={19}/>}</Button></form><div className="input-footer"><span><ShieldCheck size={14}/> Your question is evaluated against written policies</span><span>{input.length}/1000</span></div></div>
 <div className="assistant-controls"><select className="language-select" value={voiceLanguage} onChange={e=>setVoiceLanguage(e.target.value as VoiceLanguage)} aria-label="Voice language">{VOICE_LANGUAGES.map(l=><option key={l.code} value={l.code}>{l.label}</option>)}</select><button className={`location-control ${locationState}`} onClick={detectLocation} type="button" disabled={locationState==="requesting"}><LocateFixed size={16}/><span>{locationState==="ready"?"Using your current location":locationState==="requesting"?"Detecting location…":"Use my current location"}</span></button><button className={`voice-button ${voiceStatus}`} onClick={()=>void((voiceStatus!=="idle"&&voiceStatus!=="error")?stopVoice():startVoice())} type="button">{voiceStatus!=="idle"&&voiceStatus!=="error"?<MicOff size={17}/>:<Mic size={17}/>}<span>{voiceStatus!=="idle"&&voiceStatus!=="error"?"Stop Voice":"Start Voice"}</span>{voiceStatus!=="idle"&&voiceStatus!=="error"&&<span className="voice-state-dot"/>}</button></div><AnimatePresence>{voiceStatus!=="idle"&&<motion.section className="voice-panel" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:8}}><div className="voice-panel-head"><div><div className="eyebrow"><span className={voiceStatus==="error"?"muted-dot":"live-dot"}/> GEMINI LIVE</div><h3>{voiceStatus==="connecting"?"Connecting…":voiceStatus==="listening"?"Listening":voiceStatus==="speaking"?"Speaking":"Voice error"}</h3></div><Volume2 size={18}/></div><div className="voice-transcripts"><div><span>YOU</span><p>{voiceInput||"Start speaking…"}</p></div><div><span>WEATHERWISE</span><p>{voiceOutput||"Your spoken response appears here."}</p></div></div>{voiceMessage&&<div className="voice-message">{voiceMessage}</div>}</motion.section>}</AnimatePresence><div className="suggestions"><span>TRY ASKING</span>{suggestions.map(s=><button key={s} onClick={()=>void ask(s)}>{s}</button>)}</div></section>
 {turns.length>0&&<section className="conversation" aria-label="Conversation">{turns.map((turn,index)=><article className="turn" key={`${turn.at}-${index}`}><div className="user-turn"><span>YOU · {new Date(turn.at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</span><p>{turn.question}</p></div>{index<turns.length-1&&turn.answer&&<div className="assistant-turn"><span>WEATHERWISE · {turn.status?.replaceAll("_"," ").toUpperCase()}</span><p>{turn.answer}</p></div>}{index===turns.length-1&&loading&&<div className="assistant-turn pending"><span>WEATHERWISE</span><p><i className="spinner dark"/> Checking the requested forecast and policy…</p></div>}</article>)}</section>}
 <AnimatePresence>{error&&<motion.div className="error" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}>{error} <button onClick={()=>setError("")}>Dismiss</button></motion.div>}</AnimatePresence>
 <AnimatePresence>{reply&&<motion.section className="result" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.35}}>
   <div className="result-head"><div><div className="eyebrow"><span className={reply.status==="matched"?"live-dot":"muted-dot"}/>{reply.status==="no_policy"?"NO POLICY MATCH":reply.status.replaceAll("_"," ").toUpperCase()}</div><h2>Your advisory</h2></div><button className="icon-button" title="Clear conversation" onClick={()=>{void stopVoice();setReply(null);setTurns([]);sessionStorage.removeItem("weatherwise-session");setTraceOpen(false);}}><RotateCcw size={16}/></button></div>
   <p className="answer">{reply.answer}</p>
   {reply.location&&<div className="location"><MapPin size={15}/>{reply.location.name}, {reply.location.country}</div>}
   {reply.weather&&<><div className="weather-label">FORECAST SNAPSHOT <span>{reply.weather.observed_at?.replace("T"," · ")} · {reply.weather.timezone}</span></div><div className="weather-grid"><Metric icon={<Thermometer/>} label="Temperature" value={reply.weather.temperature_2m==null?"—":`${reply.weather.temperature_2m}°C`}/><Metric icon={<Wind/>} label="Wind" value={reply.weather.wind_speed_10m==null?"—":`${reply.weather.wind_speed_10m} km/h`}/><Metric icon={<Droplets/>} label="Rain chance" value={reply.weather.precipitation_probability==null?"—":`${reply.weather.precipitation_probability}%`}/><Metric icon={<Sun/>} label="UV index" value={reply.weather.uv_index==null?"—":reply.weather.uv_index}/></div></>}
   {reply.policy?.sop_id&&<div className="citation"><ShieldCheck size={17}/><div><b>{reply.policy.sop_id} · {reply.policy.title}</b><span>{reply.policy.severity} SEVERITY · DETERMINISTIC POLICY</span></div></div>}
   <button className="trace-toggle" onClick={()=>setTraceOpen(!traceOpen)}>Engineering trace <ChevronDown size={15} className={traceOpen?"turned":""}/></button>{traceOpen&&<ol className="trace">{reply.trace.map((x,i)=><li key={i}>{x}</li>)}{reply.policy?.trace?.map((x,i)=><li key={`policy-${i}`}>{x.sop_id}: {x.detail}</li>)}</ol>}
 </motion.section>}</AnimatePresence>
 <footer><span>Weather facts from <b>{reply?.weather?.source || "Open-Meteo"}</b></span><span>Safety decisions from written SOPs</span></footer></main>
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string|number}) {return <div className="metric"><span className="metric-icon">{icon}</span><span className="metric-label">{label}</span><b>{value}</b></div>}
